
["custom text"]
	#Insert the custom title screen text you want here (supports multiple lines)
	text = ["欢迎来到 EMC & FE ++ v2.0.0!"]

[versions]
	#Show which version of Minecraft the client is currently running.
	showMcVersion = true
	#Show which version of Minecraft Coder Pack (MCP) the client is running.
	showMcpVersion = false
	#Show which version of Minecraft Forge the client is running.
	showForgeVersion = true
	#Show how many mods are loaded.
	showModsLoaded = true

